# Generated by Django 3.2.7 on 2021-09-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_auto_20210921_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='type',
        ),
    ]
